server:
  port: 8080
# 连接池配置
spring:
  application:
    name: melodify
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///melodify
    username: root
    password: 18836326309


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: cn.example.melodify.pojo
